name: Deploy Application to Production

on:
 push: 
   branches: [main]

jobs:
  build: 
       runs-on: ubuntu-latest
       steps:
         - name: Checkout Code
           uses: actions/checkout@v3
           
         - name: Setup Java
           uses: actions/setup-java@v3
           with:
             distribution: 'temurin'
             java-version: '17'
             
         - name: Build project
           run: mvn clean install -DskipTests

         - name: Login Docker Hub
           run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
           
         - name: Build docker image
           run: docker build -t hmendozap/desploy_ghactions .

         - name: Push imagen Docker Hub
           run: docker push hmendozap/desploy_ghactions
           
